kind: PersistentVolume
apiVersion: v1
metadata:
  name: host-pv
spec:
  storageClassName: microk8s-hostpath
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /home/akrieg/projects/thinktank/localk8s/microk8s/hostvolume
  claimRef:
    name: host-pvc
    namespace: default
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: host-pvc
spec:
  storageClassName: microk8s-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

