apiVersion: v1
kind: Pod
metadata:
  name: mybusybox
  labels:
    app: mybusybox
spec:
  containers:
  - name: mybusybox
    image: alexkrieg.com/mybusybox
    imagePullPolicy: Never
    command: ['sh', '-c', 'sleep 3600']
